// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLT3dBibWewMTNaK6mB_DTpH1lM9PaY70',
    appId: '1:667185884270:web:19c1cb7716960774d94a7f',
    messagingSenderId: '667185884270',
    projectId: 'flutter-app-a808f',
    authDomain: 'flutter-app-a808f.firebaseapp.com',
    storageBucket: 'flutter-app-a808f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw_Qu4lKhlvEPnEddq8200PitCQVfu2oo',
    appId: '1:667185884270:android:3e31da9d65d249cfd94a7f',
    messagingSenderId: '667185884270',
    projectId: 'flutter-app-a808f',
    storageBucket: 'flutter-app-a808f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnrNjucCBhXytD2ynRNgZLUoJTIFU8hk0',
    appId: '1:667185884270:ios:b63287ed1ad8d1f3d94a7f',
    messagingSenderId: '667185884270',
    projectId: 'flutter-app-a808f',
    storageBucket: 'flutter-app-a808f.appspot.com',
    iosBundleId: 'com.example.newpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnrNjucCBhXytD2ynRNgZLUoJTIFU8hk0',
    appId: '1:667185884270:ios:3f290bf08461f52cd94a7f',
    messagingSenderId: '667185884270',
    projectId: 'flutter-app-a808f',
    storageBucket: 'flutter-app-a808f.appspot.com',
    iosBundleId: 'com.example.newpro.RunnerTests',
  );
}
